### ISSUE TITLE
HostedEventsController#index (ZeroDivisionError) "divided by 0"

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#285]
<table><tr><th>Exception</th><td>divided by 0</td></tr><tr><th>Last Occurrence</th><td>August 11, 2015 17:02:37 -0400</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/NullVoxPopuli/aeonvera/blob/0f54153096b262c24f441664c982d2a817828186/app/controllers/hosted_events_controller.rb#L27'>[app].../app/controllers/hosted_events_controller.rb:27:in `/'</a>
<a href='https://github.com/NullVoxPopuli/aeonvera/blob/0f54153096b262c24f441664c982d2a817828186/app/controllers/hosted_events_controller.rb#L27'>[app].../app/controllers/hosted_events_controller.rb:27:in `index'</a>
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
[bundle].../gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/recurring_select-1.3.1/app/middleware/recurring_select_middleware.rb:24:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
[bundle].../gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activerecord-4.2.3/lib/active_record/migration.rb:377:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/better_errors-2.1.1/lib/better_errors/middleware.rb:84:in `protected_app_call'
[bundle].../gems/better_errors-2.1.1/lib/better_errors/middleware.rb:79:in `better_errors_call'
[bundle].../gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
[bundle].../gems/newrelic_rpm-3.11.2.286/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'
[bundle].../gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'
[bundle].../gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'
[bundle].../gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'
[bundle].../gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'</pre>
Fingerprint: `0c484ad8e0ebba2c8ea55215e42c1b15375450ba`

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>August 11, 2015 17:02:37 -0400</td></tr><tr><th>URL</th><td>[GET] /hosted_events/</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>hosted_events</td></tr><tr><th>action</th><td>index</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
this was a test
