### ISSUE TITLE
# (Exceptions::FrontEndError) "Error: Assertion Failed: The URL '/user/edit' did not match any routes in your application
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:21427:21)
    at Object.Ember.default.assert (http://localhost:4200/assets/vendor.js:14575:13)
    at http://localhost:4200/assets/vendor.js:33688:24
    at tryCatch (http://localhost:4200/assets/vendor.js:56350:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:56362:17)
    at http://localhost:4200/assets/vendor.js:58261:13
    at http://localhost:4200/assets/vendor.js:36652:7
    at Queue.invokeWithOnError (http://localhost:4200/assets/vendor.js:10293:20)
    at Object.Queue.flush (http://localhost:4200/assets/vendor.js:10349:13)"

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#305]
<table><tr><th>Exception</th><td>#&lt;Exceptions::FrontEndError:0x007fd86588a140&gt;</td></tr><tr><th>Last Occurrence</th><td>August 12, 2015 22:28:01 -0400</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre></pre>
Fingerprint: `33dc0fd18ae0da4a5631da233010b5452936f901`

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>August 12, 2015 22:28:01 -0400</td></tr><tr><th>Params</th><td></td></tr></table>
