### ISSUE TITLE
# (Exceptions::FrontEndError) "TypeError: Unable to get property 'setItem' of undefined or null reference
   at persist (https://aeonvera.com/dist/assets/vendor.js:69762:9)
   at updateStore (https://aeonvera.com/dist/assets/vendor.js:69413:9)
   at setup (https://aeonvera.com/dist/assets/vendor.js:69367:9)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:69284:13)
   at tryCatch (https://aeonvera.com/dist/assets/vendor.js:56350:9)
   at invokeCallback (https://aeonvera.com/dist/assets/vendor.js:56362:9)
   at publish (https://aeonvera.com/dist/assets/vendor.js:56333:11)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:36652:7)
   at Queue.prototype.invoke (https://aeonvera.com/dist/assets/vendor.js:10284:11)
   at Queue.prototype.flush (https://aeonvera.com/dist/assets/vendor.js:10349:13)"

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#351]
<table><tr><th>Exception</th><td>#&lt;Exceptions::FrontEndError:0x007f721424d708&gt;</td></tr><tr><th>Last Occurrence</th><td>August 28, 2015 15:42:27 +0000</td></tr><tr><th>Count</th><td>11</td></tr></table>

## Stack Trace
<pre></pre>
Fingerprint: `a1e43788097e0e87b9e786fae84900d715ffd43b`

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2015 15:30:47 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>TypeError: Unable to get property &#39;setItem&#39; of undefined or null reference
   at persist (https://aeonvera.com/dist/assets/vendor.js:69762:9)
   at updateStore (https://aeonvera.com/dist/assets/vendor.js:69413:9)
   at setup (https://aeonvera.com/dist/assets/vendor.js:69367:9)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:69284:13)
   at tryCatch (https://aeonvera.com/dist/assets/vendor.js:56350:9)
   at invokeCallback (https://aeonvera.com/dist/assets/vendor.js:56362:9)
   at publish (https://aeonvera.com/dist/assets/vendor.js:56333:11)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:36652:7)
   at Queue.prototype.invoke (https://aeonvera.com/dist/assets/vendor.js:10284:11)
   at Queue.prototype.flush (https://aeonvera.com/dist/assets/vendor.js:10349:13)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr><tr><th>from_js</th><td></td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2015 15:30:51 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>TypeError: Unable to get property &#39;setItem&#39; of undefined or null reference
   at persist (https://aeonvera.com/dist/assets/vendor.js:69762:9)
   at updateStore (https://aeonvera.com/dist/assets/vendor.js:69413:9)
   at setup (https://aeonvera.com/dist/assets/vendor.js:69367:9)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:69284:13)
   at tryCatch (https://aeonvera.com/dist/assets/vendor.js:56350:9)
   at invokeCallback (https://aeonvera.com/dist/assets/vendor.js:56362:9)
   at publish (https://aeonvera.com/dist/assets/vendor.js:56333:11)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:36652:7)
   at Queue.prototype.invoke (https://aeonvera.com/dist/assets/vendor.js:10284:11)
   at Queue.prototype.flush (https://aeonvera.com/dist/assets/vendor.js:10349:13)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr><tr><th>from_js</th><td></td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2015 15:30:56 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>TypeError: Unable to get property &#39;setItem&#39; of undefined or null reference
   at persist (https://aeonvera.com/dist/assets/vendor.js:69762:9)
   at updateStore (https://aeonvera.com/dist/assets/vendor.js:69413:9)
   at setup (https://aeonvera.com/dist/assets/vendor.js:69367:9)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:69284:13)
   at tryCatch (https://aeonvera.com/dist/assets/vendor.js:56350:9)
   at invokeCallback (https://aeonvera.com/dist/assets/vendor.js:56362:9)
   at publish (https://aeonvera.com/dist/assets/vendor.js:56333:11)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:36652:7)
   at Queue.prototype.invoke (https://aeonvera.com/dist/assets/vendor.js:10284:11)
   at Queue.prototype.flush (https://aeonvera.com/dist/assets/vendor.js:10349:13)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr><tr><th>from_js</th><td></td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2015 15:31:04 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>TypeError: Unable to get property &#39;setItem&#39; of undefined or null reference
   at persist (https://aeonvera.com/dist/assets/vendor.js:69762:9)
   at updateStore (https://aeonvera.com/dist/assets/vendor.js:69413:9)
   at setup (https://aeonvera.com/dist/assets/vendor.js:69367:9)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:69284:13)
   at tryCatch (https://aeonvera.com/dist/assets/vendor.js:56350:9)
   at invokeCallback (https://aeonvera.com/dist/assets/vendor.js:56362:9)
   at publish (https://aeonvera.com/dist/assets/vendor.js:56333:11)
   at Anonymous function (https://aeonvera.com/dist/assets/vendor.js:36652:7)
   at Queue.prototype.invoke (https://aeonvera.com/dist/assets/vendor.js:10284:11)
   at Queue.prototype.flush (https://aeonvera.com/dist/assets/vendor.js:10349:13)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr><tr><th>from_js</th><td></td></tr></table></td></tr></table>
