### ISSUE TITLE
Error: ["Error while processing route: event-at-the-door.checkin","Cannot read property 'get' of null","TypeError: Cannot read property 'get' of null\n    at e.default.t.default.Route.extend.model (https://s3.amazonaws.com/aeonvera-staging/ember/assets/ae

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#513]
View details in Rollbar: [https://rollbar.com/nullvoxpopuli/aeonvera/items/32/](https://rollbar.com/nullvoxpopuli/aeonvera/items/32/)

```

Error: ["Error while processing route: event-at-the-door.checkin","Cannot read property 'get' of null","TypeError: Cannot read property 'get' of null\n    at e.default.t.default.Route.extend.model (https://s3.amazonaws.com/aeonvera-staging/ember/assets/aeonvera-97fd2aee7a0d23ce1e8aa754eb7daa51.js:4:11739)\n    at m.default.extend.deserialize (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:12:30581)\n    at Object.p [as applyHook] (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:20:10829)\n    at Object.r.runSharedModelHook (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:19:23884)\n    at Object.n.subclass.getModel (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:19:22010)\n    at https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:20:9494\n    at y (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:20:13012)\n    at b (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:20:13107)\n    at g (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:20:12915)\n    at https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js:14:8440"]
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/aeonvera-97fd2aee7a0d23ce1e8aa754eb7daa51.js", line 2, in t.default.Logger.error
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 13, in S
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 13, in I.error
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 13, in Object.M [as triggerEvent]
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 20, in Object.l [as trigger]
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 20, in Object.a.trigger
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 20, in [anonymous]
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 20, in y
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 20, in b
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-e44cafb667c496c99c14d64807ee2fb9.js", line 20, in g
```

**Comment by NullVoxPopuli** [comment]
maybe staging should use the dev build, so I can actually read the js files. :-\

**Comment by NullVoxPopuli** [comment]
this happened when trying to view the checkin list.
