### ISSUE TITLE
# (Exceptions::FrontEndError) "Ember"

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#523]
<table><tr><th>Exception</th><td>#&lt;Exceptions::FrontEndError:0x007f1c3caf2c60&gt;</td></tr><tr><th>Last Occurrence</th><td>April 27, 2016 03:32:11 +0000</td></tr><tr><th>Count</th><td>9</td></tr></table>

## Stack Trace
<pre></pre>
Fingerprint: `6a452598b76fcc0fbb262c29e64244e7e008593f`

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:32 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:34 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>

**Comment by NullVoxPopuli** [comment]
<table><tr><th>Occurred At</th><td>March 21, 2016 23:19:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>error</th><td><table><tr><th>message</th><td>Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (https://www.aeonvera.com/dist/assets/vendor.js:26107:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (https://www.aeonvera.com/dist/assets/vendor.js:88120:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:89820:16)
    at superFunction (https://www.aeonvera.com/dist/assets/vendor.js:28065:20)
    at ember$data$lib$adapters$rest$adapter$$default.extend.handleResponse (https://www.aeonvera.com/dist/assets/vendor.js:90546:30)
    at apply (https://www.aeonvera.com/dist/assets/vendor.js:32957:18)
    at superWrapper [as handleResponse] (https://www.aeonvera.com/dist/assets/vendor.js:32595:15)
    at hash.error (https://www.aeonvera.com/dist/assets/vendor.js:89916:33)
    at fire (https://www.aeonvera.com/dist/assets/vendor.js:3308:30)</td></tr></table></td></tr><tr><th>format</th><td>json</td></tr><tr><th>controller</th><td>api/errors</td></tr><tr><th>action</th><td>from_ember</td></tr></table></td></tr></table>
