### ISSUE TITLE
Delete the current-subdomain service

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#564]
View details in Rollbar: [https://rollbar.com/nullvoxpopuli/aeonvera/items/48/](https://rollbar.com/nullvoxpopuli/aeonvera/items/48/)

```

Error: ["Error: Assertion Failed: The route dance-event was not found\n    at new Error (native)\n    at Error.n (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:10:8035)\n    at https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:6:30932\n    at Object.r [as assert] (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:10:5233)\n    at d.default.extend._doTransition (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:13:13663)\n    at d.default.extend.transitionTo (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:13:9892)\n    at p.default.extend.transitionTo (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:12:30086)\n    at https://s3.amazonaws.com/aeonvera-staging/ember/assets/aeonvera-b33be927135a5f86ebff946562b21ed6.js:5:1022\n    at y (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:20:17922)\n    at b (https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js:20:18017)"]
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/aeonvera-b33be927135a5f86ebff946562b21ed6.js", line 3, in Object.t.default.Logger.error
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 14, in s
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 20, in Object.e.default.trigger
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 20, in [anonymous]
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 5, in n.invoke
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 5, in Object.n.flush
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 5, in Object.r.flush
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 5, in Object.i.end
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 5, in Object.i.run
  File "https://s3.amazonaws.com/aeonvera-staging/ember/assets/vendor-15c73750e91b2279418e9f2bfa795981.js", line 5, in Object.i.join
```

**Comment by NullVoxPopuli** [comment]
this means I have some cleanup to do.

I can get rid of the current-subdomain service
