### ISSUE TITLE
Error: ["TypeError: Cannot read property 'get' of null\n    at https://s3.amazonaws.com/aeonvera-production/ember/assets/aeonvera-5254cfc211587ee5da453dcab53ad1fc.js:1:31184\n    at y (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-59702

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#583]
View details in Rollbar: [https://rollbar.com/nullvoxpopuli/aeonvera/items/63/](https://rollbar.com/nullvoxpopuli/aeonvera/items/63/)

```

Error: ["TypeError: Cannot read property 'get' of null\n    at https://s3.amazonaws.com/aeonvera-production/ember/assets/aeonvera-5254cfc211587ee5da453dcab53ad1fc.js:1:31184\n    at y (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:18:29012)\n    at b (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:18:29107)\n    at g (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:18:28915)\n    at https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:13:13734\n    at n.invoke (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:5:3470)\n    at Object.n.flush (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:5:4002)\n    at Object.r.flush (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:5:2054)\n    at Object.a.end (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:5:6197)\n    at Object.a.run (https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js:5:7336)"]
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/aeonvera-5254cfc211587ee5da453dcab53ad1fc.js", line 3, in Object.t.default.Logger.error
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 13, in s
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 19, in Object.e.default.trigger
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 19, in [anonymous]
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 5, in n.invoke
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 5, in Object.n.flush
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 5, in Object.r.flush
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 5, in Object.a.end
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 5, in Object.a.run
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 5, in Object.a.join
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 10, in Function.l.join
  File "https://s3.amazonaws.com/aeonvera-production/ember/assets/vendor-597028cde4717fc791804a095997ff87.js", line 16, in Object.n.default.handleEvent
```

**Comment by NullVoxPopuli** [comment]
closing cause no sourcemap
